/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/3D/iPhone.glb 
Author: mister dude (https://sketchfab.com/misterdude)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-14-pro-5cb0778041a34f09b409a38c687bb1d4
Title: Iphone 14 Pro
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function iPhone(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("public/assets/3D/iPhone.glb");

  console.log(nodes);
  console.log(materials);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.Material}
            scale={13.669}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("public/assets/3D/iPhone.glb");
